import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;
public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        objeto.misobjetos.add(new objeto(1,1,1,1,1,1,1,1));
        txtInvTiempo.setText(String.valueOf(objeto.misobjetos.get(0).gettInv()));
        txtInvCosto.setText(String.valueOf(objeto.misobjetos.get(0).getCostoInv()));
        txtProdtiempo.setText(String.valueOf(objeto.misobjetos.get(0).gettProd()));
        txtProdCosto.setText(String.valueOf(objeto.misobjetos.get(0).getCostoProd()));
        txtEmpaTiempo.setText(String.valueOf(objeto.misobjetos.get(0).gettEmpa()));
        txtEmpaCosto.setText(String.valueOf(objeto.misobjetos.get(0).getCostoEmpa()));
        txtSalidaTiempo.setText(String.valueOf(objeto.misobjetos.get(0).getTsal()));
        txtSalidaCosto.setText(String.valueOf(objeto.misobjetos.get(0).getCostoSal()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtInvTiempo = new javax.swing.JTextField();
        txtProdtiempo = new javax.swing.JTextField();
        txtEmpaTiempo = new javax.swing.JTextField();
        txtSalidaTiempo = new javax.swing.JTextField();
        txtInvCosto = new javax.swing.JTextField();
        txtProdCosto = new javax.swing.JTextField();
        txtEmpaCosto = new javax.swing.JTextField();
        txtSalidaCosto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido a Monkey");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Costos (Q/s)");

        jLabel3.setText("Tiempo (S)");

        jLabel4.setText("Inventario:");

        jLabel5.setText("Produccion:");

        jLabel6.setText("Empaquetado:");

        jLabel7.setText("Salida:");

        jButton1.setText("Iniciar Simulacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpaTiempo)
                            .addComponent(txtSalidaTiempo)
                            .addComponent(txtProdtiempo)
                            .addComponent(txtInvTiempo)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProdCosto)
                            .addComponent(txtInvCosto)
                            .addComponent(txtEmpaCosto)
                            .addComponent(txtSalidaCosto)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInvTiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtInvCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProdtiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmpaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSalidaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalidaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        if ( !txtInvTiempo.getText().equals("")  && 
                !txtInvCosto.getText().equals("") && 
                !txtProdtiempo.getText().equals("") && 
                !txtProdCosto.getText().equals("") &&
                !txtEmpaTiempo.getText().equals("") && 
                !txtEmpaCosto.getText().equals("") && 
                !txtSalidaTiempo.getText().equals("") && 
                !txtSalidaCosto.getText().equals("") ) {
            
            try {
                
                objeto.misobjetos.get(0).settInv(Integer.parseInt(txtInvTiempo.getText()));
                objeto.misobjetos.get(0).setCostoInv(Integer.parseInt(txtInvCosto.getText()));
                objeto.misobjetos.get(0).settProd(Integer.parseInt(txtProdtiempo.getText()));
                objeto.misobjetos.get(0).setCostoProd(Integer.parseInt(txtProdCosto.getText()));
                objeto.misobjetos.get(0).settEmpa(Integer.parseInt(txtEmpaTiempo.getText()));
                objeto.misobjetos.get(0).setCostoEmpa(Integer.parseInt(txtEmpaCosto.getText()));
                objeto.misobjetos.get(0).setTsal(Integer.parseInt(txtSalidaTiempo.getText()));
                objeto.misobjetos.get(0).setCostoSal(Integer.parseInt(txtSalidaCosto.getText()));
                
                
                
                
                
                
                this.setVisible(false);
            MenuInicial u = new MenuInicial();
            u.setVisible(true); 
            
            //hilos2.cosa = 0;
            //hilos2.val1 = 30;
            hilos.parametro = true;
            
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Porfavor ingrese unicamente numeros enteros.");
            }                                   
        } else {
            JOptionPane.showMessageDialog(null, "Por favor asegurese de que todos los campos esten llenos.");
        }
        
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEmpaCosto;
    private javax.swing.JTextField txtEmpaTiempo;
    private javax.swing.JTextField txtInvCosto;
    private javax.swing.JTextField txtInvTiempo;
    private javax.swing.JTextField txtProdCosto;
    private javax.swing.JTextField txtProdtiempo;
    private javax.swing.JTextField txtSalidaCosto;
    private javax.swing.JTextField txtSalidaTiempo;
    // End of variables declaration//GEN-END:variables
    
}
