
import java.awt.Color;
import java.awt.Graphics;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dominic
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        
        jButton1.setEnabled(false);
        this.getContentPane().setBackground(Color.orange);
        
        this.setLocationRelativeTo(null);
        
        hilos hilo1 = new hilos();
        hilo1.start();
        
        hilos2 hilo2 = new hilos2();
        hilo2.start();
        
        
        
        
        
        

        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monkey (simulacion)");
        setBackground(new java.awt.Color(0, 0, 255));

        jButton1.setText("Regresar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("00:00");

        jLabel2.setText("0");

        jLabel3.setText("0");

        jLabel4.setText("0");

        jLabel5.setText("0");

        jLabel6.setText("30");

        jLabel7.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(183, 183, 183))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(274, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FileWriter archivo = null;
        
        int total = (objeto.misobjetos.get(0).tInv * objeto.misobjetos.get(0).getCostoInv()*30) +
                (objeto.misobjetos.get(0).tProd * objeto.misobjetos.get(0).getCostoProd()*30) +
                (objeto.misobjetos.get(0).tEmpa * objeto.misobjetos.get(0).getCostoEmpa()*30) +
                (objeto.misobjetos.get(0).tsal * objeto.misobjetos.get(0).getCostoSal()*30);

        try {
            archivo = new FileWriter("Reporte.html");
            
            archivo.write("<html><head><title>Reporte de simulacion </title></head><body> \n");
            archivo.write("<h1>     REPORTE DE LOS SECTORES DE LA SIMULACION   "+ "<h1>");
            archivo.write("<h1> Costo del sector Inventario: "+ (objeto.misobjetos.get(0).tInv * objeto.misobjetos.get(0).getCostoInv()*30) + "<h1>");
            archivo.write("<h1> Costo del sector Produccion: "+ (objeto.misobjetos.get(0).tProd * objeto.misobjetos.get(0).getCostoProd()*30)+ "<h1>");
            archivo.write("<h1> Costo del sector Empaquetado: "+ (objeto.misobjetos.get(0).tEmpa * objeto.misobjetos.get(0).getCostoEmpa()*30)+ "<h1>");
            archivo.write("<h1> Costo del sector Salda:  "+ (objeto.misobjetos.get(0).tsal * objeto.misobjetos.get(0).getCostoSal()*30)+ "<h1>");
            archivo.write("<h1> Costo Total: "+ total + "<h1>");
            archivo.write("<h1> Nombre: Dominic Juan Pablo      Carnet: Ruano Perez 202200075 <h1>");
            
            archivo.write(    "</body></html>");
            archivo.close();

            
        } catch (IOException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
            Menu u = new Menu();
            u.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables


        @Override
    public void paint(Graphics g){
        super.paint(g);
        
        g.setColor(Color.magenta);
        g.fillRoundRect(20, 180, 140, 100, 10, 10);
        
        g.setColor(Color.BLACK);
        g.drawString("Empaquetado: ", 25, 195);
        
        g.setColor(Color.green);
        g.fillRoundRect(240, 180, 140, 100, 10, 10);
        
        g.setColor(Color.BLACK);
        g.drawString("Produccion: ", 245, 195);
        
        
        g.setColor(Color.pink);
        g.fillRoundRect(20, 380, 140, 100, 10, 10);
        
        g.setColor(Color.BLACK);
        g.drawString("Salida: ", 25, 395);
        
        g.setColor(Color.blue);
        g.fillRoundRect(240, 380, 140, 100, 10, 10);
        
        g.setColor(Color.white);
        g.drawString("Inventario: ", 245, 395);
        
        
        int[] puntosx = {0,70,0};
        int[] puntosy = {290,330,370};
        g.setColor(Color.red);
        g.fillPolygon(puntosx, puntosy, 3);
        g.setColor(Color.BLACK);
        g.drawString("Final: ", 10, 335);
        
        int[] puntosx2 = {400,330,400};
        int[] puntosy2 = {290,330,370};
        g.setColor(Color.yellow);
        g.fillPolygon(puntosx2, puntosy2, 3);
        g.setColor(Color.BLACK);
        g.drawString("Inicio: ", 340, 335);
        
        
        g.drawLine(330, 330, 300, 330);
        g.drawLine(300, 330, 300, 380);
        
        g.drawLine(260, 380, 260, 280);
        g.drawLine(140, 380, 140, 280);
        
        g.drawLine(160, 230, 240, 230);
        
        g.drawLine(70, 330, 100, 330);
        g.drawLine(100, 330, 100, 380);
        
        
        int[] puntosx3 = {290,300,310};
        int[] puntosy3 = {370,380,370};
        
        g.setColor(Color.black);
        g.fillPolygon(puntosx3, puntosy3, 3);
        
        int[] puntosx4 = {250,260,270};
        int[] puntosy4 = {290,280,290};
        
        g.setColor(Color.black);
        g.fillPolygon(puntosx4, puntosy4, 3);
        
        int[] puntosx5 = {170,160,170};
        int[] puntosy5 = {220,230,240};
        
        g.fillPolygon(puntosx5, puntosy5, 3);
        
        int[] puntosx6 = {80,70,80};
        int[] puntosy6 = {320,330,340};
        
        g.fillPolygon(puntosx6, puntosy6, 3);
        
        int[] puntosx7 = {130,140,150};
        int[] puntosy7 = {290,280,290};
        
        g.fillPolygon(puntosx7, puntosy7, 3);
        
        
        g.drawString("Tiempo Transcurrido:", 150, 100); 
    }

}
